interface=$DNSMASQ_IF
bind-dynamic # Follow addresses added later

port=53
cache-size=0 # Disable cache

log-queries

domain=$DOMAIN
local=/$DOMAIN/
expand-hosts

dhcp-range=$DHCP_RANGE_START,$DHCP_RANGE_END,$DHCP_NETMASK,$DHCP_LEASE_TIME
dhcp-option=option:router,$ROUTER_ADDRESS
dhcp-option=option:dns-server,$ROUTER_ADDRESS
dhcp-option=option:domain-name,$DOMAIN
dhcp-authoritative
dhcp-leasefile=/var/lib/hermes/dnsmasq.leases
