interface=$LAN_IF

port=53
cache-size=0 # Disable cache

log-queries

domain=$DOMAIN
local=/$DOMAIN/
expand-hosts

dhcp-range=$DHCP_RANGE_START,$DHCP_RANGE_END,$DHCP_NETMASK,$DHCP_LEASE_TIME
dhcp-option=option:router,$LAN_ADDRESS
dhcp-option=option:dns-server,$LAN_ADDRESS
dhcp-authoritative
