vrrp_instance HERMES {
    interface $LAN_IF
    virtual_router_id $KEEPALIVED_VIRTUAL_ROUTER_ID
    advert_int 1

    virtual_ipaddress {
        $LAN_ADDRESS/24 dev $LAN_IF
        $WAN_ADDRESS dev $WAN_IF
    }
}
