#!/command/with-contenv sh

echo "Configuring $LAN_IF"
ip link set dev "$LAN_IF" up

if [ "$ENABLE_KEEPALIVED" = "true" ]; then
  echo "ENABLE_KEEPALIVED=true, leaving $LAN_ADDRESS on $LAN_IF to keepalived"
else
  # Replace makes it indempotent
  ip address replace "$LAN_ADDRESS/24" dev "$LAN_IF"
  echo "Address set to $LAN_ADDRESS/24 on interface $LAN_IF"
fi

echo "Configuring $WAN_IF"
ip link set dev "$WAN_IF" up

if [ "$ENABLE_KEEPALIVED" = "true" ]; then
  echo "ENABLE_KEEPALIVED=true, leaving $WAN_ADDRESS and the default route on $WAN_IF to keepalived"
else
  # Replace makes it indempotent
  ip address replace "$WAN_ADDRESS/$WAN_NETMASK" dev "$WAN_IF"
  echo "Address set to $WAN_ADDRESS/$WAN_NETMASK on interface $WAN_IF"

  ip route replace default via "$WAN_GATEWAY" dev "$WAN_IF"
  echo "Default route set via $WAN_GATEWAY on interface $WAN_IF"
fi
